### ISSUE TITLE
Suggestion: auto update

### ISSUE THREAD

**Issue by user122336** [acquitelol/CutestBypass#10]
Hi,

Is it possible to make the extension auto update? For example, instead of the main script being hosted on the user's pc, it is hosted on a CDN? Maybe use jsdelivr?

Thanks

**Comment by acquitelol** [comment]
I was planning to do this but if I were to do it, it would lower security standards for the extension which are very high for me. The way I could do it is an opt-in updating system in the extension bundle itself where it downloads and replaces itself and that will come eventually.

**Comment by user122336** [comment]
I understand. Will this be expected in the next update?

**Comment by acquitelol** [comment]
Well right now I'm still just mostly fixing small issues however expect it in the next minor feature release (3.5.0)

**Comment by user122336** [comment]
ok thanks
