### ISSUE TITLE
how to fix?

### ISSUE THREAD

**Issue by PurpleBox42** [acquitelol/CutestBypass#12]
this error when i import:

File       ~\Downloads\azalea-sparx-v2
Error    Manifest file is missing or unreadable
Could not load manifest.

**Comment by acquitelol** [comment]
Did you download the source code or bundled zip from releases?

If you downloaded the source code this is incorrect, please read the README.md for installation instructions.

If you downloaded the bundled zip from releases, please try selecting the folder inside the folder you just selected instead. Basically, make sure that the folder you select has a manifest.json file inside.

**Comment by acquitelol** [comment]
Stale issue.
