### ISSUE TITLE
COLLAB?

### ISSUE THREAD

**Issue by sparx-solver** [acquitelol/CutestBypass#13]
i am the owner of a discord bot that solves sparx questions would u be interested in a collab? if u wanan find out more or collab dm me on discord my name is "sparxsolver"

**Comment by c0lide** [comment]
Not affiliated with us or [SparxSolver](https://github.com/c0lide/SparxSolver)

**Comment by acquitelol** [comment]
> Not affiliated with us or [SparxSolver](https://github.com/c0lide/SparxSolver)

You're acting as if you wrote any of the code in that project.

Leave Azalea alone. Write your own thing. Do you know how demotivating it is to spend so long working on an update then skids like you take the code and claim they wrote it themselves?

The reason why so many cool projects turn closed-source is because of people like you. Can you seriously not see the harm you're doing to the project you're stealing code from?

**Comment by acquitelol** [comment]
> i am the owner of a discord bot that solves sparx questions would u be interested in a collab? if u wanan find out more or collab dm me on discord my name is "sparxsolver"

Anyways how would this even work as a collaboration, considering that's a Discord bot. I don't explicitly advertise Azalea anywhere, so collaboration wouldn't result in any real benefits for either of us 🤷🏻‍♀️

**Comment by sparx-solver** [comment]
Well 

> > i am the owner of a discord bot that solves sparx questions would u be interested in a collab? if u wanan find out more or collab dm me on discord my name is "sparxsolver"
> 
> Anyways how would this even work as a collaboration, considering that's a Discord bot. I don't explicitly advertise Azalea anywhere, so collaboration wouldn't result in any real benefits for either of us 🤷🏻‍♀️

i was thinking that we could advertise both our services mutually since you have the bookworks solver we have the queston solver

**Comment by acquitelol** [comment]
> Well
> 
> > > i am the owner of a discord bot that solves sparx questions would u be interested in a collab? if u wanan find out more or collab dm me on discord my name is "sparxsolver"
> > 
> > 
> > Anyways how would this even work as a collaboration, considering that's a Discord bot. I don't explicitly advertise Azalea anywhere, so collaboration wouldn't result in any real benefits for either of us 🤷🏻‍♀️
> 
> i was thinking that we could advertise both our services mutually since you have the bookworks solver we have the queston solver

I see, I will think about it and get back to you c:
