### ISSUE TITLE
Confused a bit

### ISSUE THREAD

**Issue by Scriptifer** [acquitelol/CutestBypass#16]
So I added it now but I actually found out its asking me did I write it down? Well, why don't you make it so it writes the page down like this and then ask the user to print it out so I can stick it into my Sparx book:
(date underlined) Sparx
(bookwork code) (question and answer)

**Comment by acquitelol** [comment]
Could you clarify what you mean? When Sparx asks you if you wrote something down, you don't need to **physically** write it down. Azalea handles that for you, and displays the answer to bookwork checks in them when they appear, aswell as in the bookwork tab. If you still want to write it down in your Sparx book, you can always open the "Bookwork" tab in the settings at the top right of Sparx, and write down each question and answer manually.

There is no current way to make a printable version of questions and answers that look like it was written in Microsoft Word or similar, sorry!

Thanks, 
Rosie <3

**Comment by acquitelol** [comment]
Done, partially, as exporting bookwork data was implemented. If you have any further requests please reply to this issue or make a new one <3
