### ISSUE TITLE
Sparx Default Colours?

### ISSUE THREAD

**Issue by RealSandy** [acquitelol/CutestBypass#18]
Quick question, what are the default Sparx Maths colours, and could you include them as a theme?

**Comment by acquitelol** [comment]
Actually, this has already been implemented and will be part of the next update! I just turn off the custom colors altogether for this theme, and it's also the default from now on, instead of pink. :3

**Comment by RealSandy** [comment]
:D

**Comment by acquitelol** [comment]
The update is out now! Give it a try whenever you get a chance and let me know how it goes c:
