### ISSUE TITLE
update response

### ISSUE THREAD

**Issue by sutemandrill** [acquitelol/CutestBypass#19]
Hey Rosie,

I wanted to drop you a quick note to express my appreciation for your extension—it's been a game-changer for me. 🚀

I've been exploring the code and noticed a few vulnerabilities that could potentially compromise the obfuscation and allow for “rebranding”. I believe addressing these issues could enhance the security of your extension.

- No code obfuscation
- No Validator (easy to change to other users etc)

Feel free to check out my fork, where i have highlighted the vulnerabilities and tested the ease of “rebranding”.

**Comment by acquitelol** [comment]
As of 3.5.0, a validator and code obfuscation have actually been implemented. In general, as the extension is open source, removing them is never too difficult, which is why the extension is not licensed and is under copyright only.

Thank you though!
~ Rosie <3
