### ISSUE TITLE
Cross-platform

### ISSUE THREAD

**Issue by sutemandrill** [acquitelol/CutestBypass#20]

**Comment by acquitelol** [comment]
I mean theoretically, that shouldn't be too bad to do

For exporting just take the current bookwork codes from local storage, put them in a JSON file, and prompt the user to download it

For importing, prompt the user to select a file, take the file contents, parse them as json, and merge them to the existing bookwork codes

Will do soon:tm:

**Comment by sutemandrill** [comment]
to make it easy, make a UI in settings for import/export

**Comment by acquitelol** [comment]
Of course :3

**Comment by acquitelol** [comment]
[Done!](https://github.com/acquitelol/azalea/commit/536bd866315962834a2266e895398b243929c02c) Azalea should update automatically, unless you have your updater disabled. Please let me know if it works correctly~

Thanks, Rosie <3
