### ISSUE TITLE
Please refresh the page.

### ISSUE THREAD

**Issue by Sylvorus** [acquitelol/CutestBypass#21]
When trying to access azalea's settings in the sparx maths website, it asks me to reload the page instead. When starting a new task it asks me to refresh the page.
![image](https://github.com/acquitelol/azalea/assets/65714920/efe3b236-62c6-4dd6-8418-72675ff23a94)

**Comment by acquitelol** [comment]
What version of Azalea do you have installed?

**Comment by Sylvorus** [comment]
Latest version, but I reverted back to 3.4.1 and everything functioned fine. Also on the latest it constantly says "Azalea is debugging this page" on the top

**Comment by acquitelol** [comment]
> Latest version, but I reverted back to 3.4.1 and everything functioned fine. Also on the latest it constantly says "Azalea is debugging this page" on the top
> 
> 

Could you open Developer Tools and tell me if there are any red (error) logs when that reload message appears?

That message is called an error boundary and is used to display that an error happened while rendering (instead of just displaying a white screen). Usually there are logs in the console providing more information when these error boundaries are triggered.

Also sorry for not responding I've been busy with school aha~

Thank you, Rosie

**Comment by Sylvorus** [comment]
Okay, I saw the logs, turned out when I turned off ublock origin everything worked fine.

**Comment by Sylvorus** [comment]
![image](https://github.com/acquitelol/azalea/assets/65714920/0ae5cd12-e5de-4d2b-b516-3aea454ff8fb)

**Comment by Sylvorus** [comment]
![image](https://github.com/acquitelol/azalea/assets/65714920/c7713283-07a5-469a-994e-91c6206fcaf9)
this is when i try to open settings while it still says "azalea is debugging this page"

**Comment by acquitelol** [comment]
> Okay, I saw the logs, turned out when I turned off ublock origin everything worked fine.

Oh lmao, interesting. For the record, none of those errors are from Azalea. Errors regarding Azalea will usually include the word Azalea in bold text before the error itself or it'll say `React minified error #xyz` or something similar.

**Comment by Sylvorus** [comment]
interesting lol, it only does this when both extensions are running together
