### ISSUE TITLE
Hey!👋

### ISSUE THREAD

**Issue by alexlostorto** [acquitelol/CutestBypass#22]
Hi @acquitelol !

I absolutely love this project, and I'm sooo impressed with how cleanly structured your code is as well as how nicely you made it.

I was just wondering, did you look at my project [Magic Notes](https://github.com/alexlostorto/magic-notes) before creating yours? Or did we just happen to coincidentally create a browser extension that solves bookwork checks with colour themes??

This project branched off from mine too: [Sparx Solver](https://github.com/najmajmal/sparxmaths/)

I'm interested in how you learned to write in TypeScript so well and became insanely consistent with all your comments/documentation throughout your code.

TypeScript looks super confusing to me (let alone React) so any support would be much appreciated <3

**Comment by c0lide** [comment]
Hey

**Comment by acquitelol** [comment]
Hi ~!! — Thank you :3

I, of course, did acknowledge that your extension existed, however I wanted to completely take my own approach on it altogether, and therefore no code should be similar between the two.

I am also a mobile client mod developer for Discord in my spare time, which involves modifying the mobile client of Discord in similar methods to this but with React Native, patching components and modules, so naturally my expertise carries over to Azalea too. I have been developing my skills in terms of client modifications for a bit over a year, which is where I learned TypeScript and React, etc. 🤷🏼‍♀️  It also helps that I am part of a big organization of like-minded silly client mod developers who I can rely upon to help me improve or solve issues 💖 

- Rosie<3

**Comment by alexlostorto** [comment]
Thank you so much for your detailed reply!!

 It really blows my mind how you're able to do all of this - I wish you all the best for the future 😊

**Comment by c0lide** [comment]
Kbro
