### ISSUE TITLE
bookwork check answers not showing?

### ISSUE THREAD

**Issue by user122336** [acquitelol/CutestBypass#25]
I just started using the newest version of this extension (3.6.0) and it has injected successfully into sparx, but when a bookwork check comes up, it does not show the saved answers. Any help?

**Comment by acquitelol** [comment]
Could you send a screenshot of what it *does* show?

**Comment by user122336** [comment]
It just shows what it would show normally without the extension, doesnt show any answers. I got the answers from the bookwork tab, otherwise I'd be screwed lol
![image](https://github.com/acquitelol/azalea/assets/147195058/8b585e06-51c8-47c8-861e-495cb1b1bccd)

**Comment by acquitelol** [comment]
I see. I'll look into this soon. Thanks! (I probably messed up the patch when I tried to make it more exact so it doesn't patch into the skills section)

**Comment by acquitelol** [comment]
[Fixed](https://github.com/acquitelol/azalea/releases/latest)
