### ISSUE TITLE
Dosent work.

### ISSUE THREAD

**Issue by kincho4** [acquitelol/CutestBypass#3]
![image](https://github.com/acquitelol/azalea/assets/75807467/81d3287d-a7dc-4d3d-a5e5-d6d2bc4842be)

**Comment by kincho4** [comment]
extention dosent get the answers

**Comment by NajmAjmal-old** [comment]
Hi @acquitelol, 

You have stated your extension is a "bookwork-bypass", yet @kincho4 is still experiencing bookwork code checks. Is there a way to access saved bookwork codes etc.

Thanks, Najm

**Comment by frosted13** [comment]
They said that they will work on it end of this week "it (should|might) be working by the end of next week if i have time to work on it"

**Comment by acquitelol** [comment]
> extention dosent get the answers

At the moment, the bookwork-bypass code is still WIP, as I'm working on styling it to be visually appealing. If you want to access whatever answer is saved in that bookwork code, you can access it on that build of Azalea by running `azalea.handlers.storages.bookwork.get('2E')` in your console and expanding the result.

In versions in the future, the 3 most recently saved answers to that bookwork code will be displayed in the bookwork check, aswell as it automatically selecting the answer that matches and submitting it automatically (if it can find it). Preview of this can be seen below:
<img width="811" alt="image" src="https://github.com/acquitelol/azalea/assets/94182437/30524d6b-634e-452b-8408-5aa52cc5d8e2">

**Comment by acquitelol** [comment]
Note that it *was* working before Sparx redid their internal code, and that's why the feature is promised in the README.md~

I didn't remove it because the feature will be coming back, it's just still work in progress.

**Comment by kincho4** [comment]
Thanks for the clarification
