### ISSUE TITLE
Unexpected Application Error

### ISSUE THREAD

**Issue by Sylvorus** [acquitelol/CutestBypass#5]
Cannot read properties of undefined (reading 'join')
![image](https://github.com/acquitelol/azalea/assets/65714920/a2bda1da-d9aa-4bc3-a418-a50bc173a06c)

**Comment by acquitelol** [comment]
Where is this shown? On the home page?

**Comment by Sylvorus** [comment]
It's shown when a bookmark check is supposed to appear.

**Comment by acquitelol** [comment]
Oh okay, let me look into that quickly.

**Comment by Sylvorus** [comment]
Thank you!

**Comment by acquitelol** [comment]
Alright, please try [3.3.1](https://github.com/acquitelol/azalea/releases/tag/azalea-1694907479)

**Comment by Sylvorus** [comment]
I'll let you know if it works.

**Comment by Sylvorus** [comment]
Okay now the bookmark check appears for a split second, then a different error:
![image](https://github.com/acquitelol/azalea/assets/65714920/1704b5b8-db3e-47bd-99f8-2892fcba2b5e)

**Comment by acquitelol** [comment]
Please note that if no answers appear below the text that says it will display the most recent answers or similar, that's because no answers were stored for that bookwork code yet.

**Comment by acquitelol** [comment]
> Okay now the bookmark check appears for a split second, then a different error: ![image](https://user-images.githubusercontent.com/65714920/268475595-1704b5b8-db3e-47bd-99f8-2892fcba2b5e.png)

Okay I think I know how to fix this altogether give me a moment

**Comment by Sylvorus** [comment]
Alright

**Comment by acquitelol** [comment]
Alright, so it was basically already fixed I just needed to open a bookwork check to make sure - should work now, please try [3.3.2](https://github.com/acquitelol/azalea/releases/tag/azalea-1694909015)

**Comment by Sylvorus** [comment]
Alright Thanks

**Comment by Sylvorus** [comment]
![image](https://github.com/acquitelol/azalea/assets/65714920/96bfe814-0119-4572-8d8f-80e127f4db55)
at this point i think its my problem

**Comment by acquitelol** [comment]
> ![image](https://github.com/acquitelol/azalea/assets/65714920/96bfe814-0119-4572-8d8f-80e127f4db55)
> 
> at this point i think its my problem 

Aha fun! Can you just quickly run `azalea.handlers.storages.bookwork.get("<bookwork code>")` and tell me the output? I'm pretty sure it's an issue where it's trying to render undefined, as no answer is stored, so I'll just need to do a few extra checks I guess

**Comment by Sylvorus** [comment]
Yeah, that works fine, its printed in a different format as before the 3.3.0 update but I assume thats intentional.

**Comment by acquitelol** [comment]
Oh, right. I completely forgot about backwards compatibility from the old format lmaooo

I would recommend that you run `azalea.handlers.storages.bookwork.clear()` to get rid of all of the answers stored in the old format however tomorrow I'll implement a backwards compatible system to convert old bookwork codes into the new format

**Comment by Sylvorus** [comment]
Ohhh alright, or you could just make it autoclear when it detects a new version!

**Comment by Sylvorus** [comment]
I'll let you know if I encounter any more errors. Thanks!

**Comment by acquitelol** [comment]
No problem! 💖

**Comment by acquitelol** [comment]
> Ohhh alright, or you could just make it autoclear when it detects a new version!

This wouldn't work the best because if someone were to do some question right before updating then it would clear whatever they had stored before lol

If they then get a bookwork check on that answer that was deleted then bye bye question !!!

However tbf the system before this update didn't display the bookwork code in the UI so the only way people would access it would be through console soooooo idk lol

**Comment by Sylvorus** [comment]
Oh right lol

**Comment by Sylvorus** [comment]
![image](https://github.com/acquitelol/azalea/assets/65714920/c078013d-25a8-453e-b5c8-1556ca22387b)
found another issue

**Comment by Sylvorus** [comment]
![image](https://github.com/acquitelol/azalea/assets/65714920/1ba3cc35-120a-4f42-bd9c-362b00092bbf)
i think its just the ui

**Comment by acquitelol** [comment]
Actually, I did experience this myself whilst showing my friend how it worked

I'll fix it in the next release :3

**Comment by acquitelol** [comment]
> ![image](https://github.com/acquitelol/azalea/assets/65714920/c078013d-25a8-453e-b5c8-1556ca22387b)
> 
> found another issue

The 'wrappers failed to query' thing can be ignored as that's for the part that captures the answers, not the part that displays them in the bookwork check

However yeah until the next release I would recommend zooming out a bit lmao

**Comment by Sylvorus** [comment]
Alright thanks lol, eager to see how this project develops. Will you still develop it even after you finish school?

**Comment by acquitelol** [comment]
> Alright thanks lol, eager to see how this project develops. Will you still develop it even after you finish school?

I'm pretty sure that my Sparx access is revoked after I finish Y11 (at the end of this year) however I will license the code and allow other developers to continue maintaining it when I do lose access ;D

**Comment by Sylvorus** [comment]
Damn. If you want I can give you access to my account, it will only last for another year though.

**Comment by acquitelol** [comment]
> Damn. If you want I can give you access to my account, it will only last for another year though.

🤷🏻‍♀️ there's still plenty of time until May next year lol

**Comment by Sylvorus** [comment]
Yeah I guess you're right

**Comment by c0lide** [comment]
> > Alright thanks lol, eager to see how this project develops. Will you still develop it even after you finish school?
> 
> I'm pretty sure that my Sparx access is revoked after I finish Y11 (at the end of this year) however I will license the code and allow other developers to continue maintaining it when I do lose access ;D

i have noticed a similar project called sintco sparxmaths solver. and there are some issues going on related to copyright and licenses. why is this an issue now, when later you will license the code to a licence to allow other devs to continue building this.

**Comment by acquitelol** [comment]
@Sylvorus as of [this commit](https://github.com/acquitelol/azalea/commit/b0c2a4106ff638fd594d47c6f8eb3c188ebfcd52) (3.4.0) the UI should now display correctly in bookwork checks!

**Comment by Sylvorus** [comment]
>woop woop
