### ISSUE TITLE
[Suggestion] Just an Idea

### ISSUE THREAD

**Issue by sourcive** [acquitelol/CutestBypass#9]
Is it possible to implement an image to text ai into this and add an auto-solve?

**Comment by acquitelol** [comment]
Yeah, of course it's possible, but AI gets it wrong really easily and at that point it's probably faster to just complete the question yourself than to try to steer the AI to do it for you;

**Comment by approxit1** [comment]
yeah u can use senai's discord bot which i offer for free :D https://discord.gg/S3wFkfw5
![image](https://github.com/acquitelol/azalea/assets/106334398/24bcb296-6bfb-426a-977e-4c113393472b)
